# Generated by Django 2.1.4 on 2018-12-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodsStore', '0008_migration_with_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.IntegerField(),
        ),
    ]
